repos:
# YAML linting and general cleanups
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # Flake8: Python linter
  - repo: https://github.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
  # Isort: Python import linter/formatter
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
        types: [ python ]
  # Black: Python code formatter
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  # Mypy: Python type-checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        # If needed, add other stub packages corresponding to libraries that don't use inline types.
        # See http://mypy-lang.blogspot.com/2021/06/mypy-0900-released.html for more details.
        additional_dependencies: [ types-toml==0.1.5 ]
  # ShellCheck: shell script analysis tool
  #- repo: https://github.com/shellcheck-py/shellcheck-py
  #  rev: v0.7.2.1
  #  hooks:
  #    - id: shellcheck
