name: r
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::hdf5
  - conda-forge::r-essentials
  - conda-forge::libblas=3.8.0=21_mkl
  - conda-forge::r-rcurl
  - conda-forge::r-biocmanager
  - conda-forge::r-cairo
  - conda-forge::r-hdf5r
  
  
  