CPal_default = c(
  "#1F77B4", "#FF7F0E", "#279E68", "#D62728", "#AA40FC", "#8C564B", "#E377C2", "#B5BD61", "#17BECF", "#AEC7E8",
  "#FFBB78", "#98DF8A", "#FF9896", "#C5B0D5", "#C49C94", "#F7B6D2", "#DBDB8D", "#9EDAE5", "#AD494A", "#8C6D31",
  "#E31A1C", "#FFD700", "#771122", "#777711", "#1F78B4", "#68228B", "#AAAA44", "#60CC52", "#771155", "#DDDD77",
  "#774411", "#AA7744", "#AA4455", "#117744", "#000080", "#44AA77", "#AA4488", "#DDAA77", "#D9D9D9", "#BC80BD",
  "#FFED6F", "#7FC97F", "#BEAED4", "#FDC086", "#FFFF99", "#386CB0", "#F0027F", "#BF5B17", "#666666", "#1B9E77",
  "#D95F02", "#7570B3", "#E7298A", "#66A61E", "#E6AB02", "#A6761D", "#A6CEE3", "#B2DF8A", "#33A02C", "#FB9A99",
  "#FDBF6F", "#FF7F00", "#CAB2D6", "#6A3D9A", "#B15928", "#FBB4AE", "#B3CDE3", "#CCEBC5", "#DECBE4", "#FED9A6",
  "#FFFFCC", "#E5D8BD", "#FDDAEC", "#F2F2F2", "#B3E2CD", "#FDCDAC", "#CBD5E8", "#F4CAE4", "#E6F5C9", "#FFF2AE",
  "#F1E2CC", "#CCCCCC", "#E41A1C", "#377EB8", "#4DAF4A", "#984EA3", "#FFFF33", "#A65628", "#F781BF", "#999999",
  "#66C2A5", "#FC8D62", "#8DA0CB", "#E78AC3", "#A6D854", "#FFD92F", "#E5C494", "#B3B3B3", "#8DD3C7", "#FFFFB3",
  "#BEBADA", "#FB8072", "#80B1D3", "#FDB462", "#B3DE69", "#FCCDE5"
)

.default_ggtheme <-  ggplot2::theme(axis.title = element_blank(),
        axis.text = ggplot2::element_blank(),
        axis.ticks = ggplot2::element_blank(),
        panel.background = ggplot2::element_blank(),
        legend.title = ggplot2::element_blank(),
        legend.background = ggplot2::element_blank(),
        legend.key = ggplot2::element_blank(),
        plot.margin = grid::unit(c(1,1,1,1),"lines"))

#' Main ACTIONet plotting functions
#'
#' @param ace 'ACTIONetExperiment' object or numeric matrix.
#' @param label_attr Character vector of length NROW(ace) or colname of 'colData(ace)' containing cell labels of interest (clusters, celltypes, etc.).
#' @param color_attr Character vector of length NROW(ace) or colname of 'colData(ace)' containing hex colors to use for each point, or matrix/data.frame containing RGB values to pass to grDevices::rgb().
#' @param trans_attr Numeric vector of length NROW(ace) or colname of 'colData(ace)' used to compute point transparency (smaller values are more transparent).
#' @param trans_fac Transparency modifier (default:1.5)
#' @param trans_th Minimum Z-score for which points with 'scale(trans_attr) < trans_th' are masked.
#' @param point_size Size of points in ggplot (default:1).
#' @param stroke_size Size of points outline (stroke) in ggplot (default:point_size*0.1).
#' @param stroke_contrast_fac Factor by which to darken point outline for contrast (default:0.1).
#' @param palette Color palette. character vector of hex colors or a palette name to pass to 'ggpubr::get_palette()').
#' @param add.text Whether or not to add labels on the top of ACTIONet plot
#' @param show_legend Show legend based on labels. Ignored if 'label_attr=NULL' or 'color_attr!=NULL' (default:'TRUE').
#' @param add.states Whether or not to include interpolated cell state positions in the plot
#' @param coordinate_attr Name of entry in colMaps(ace) containing the plot coordinates (default:'ACTIONet2D').
#' @param color_slot Name of entry in colMaps(ace) containing RGB values for default point colors generated by 'layout_ACTIONet()'. Used only if no other coloring parameters are given or valid (default:'denovo_color').
#'
#' @return Visualized ACTIONet
#'
#' @examples
#' ace = run.ACTIONet(sce)
#' plot.ACTIONet(ace, ace$assigned_archetype, transparency.attr = ace$node_centrality)
#' @export
.plot_ACTIONet2D <- function(
  ace,
  label_attr = NULL,
  color_attr = NULL,
  trans_attr = NULL,
  trans_fac = 1.5,
  trans_th = -0.5,
  point_size = 1,
  stroke_size = point_size * 0.1,
  stroke_contrast_fac = 0.1,
  palette = CPal_default,
  add.text = TRUE,
  show_legend = TRUE,
  add.backbone = FALSE,
  arch.size.factor = 3,
  coordinate_attr = "ACTIONet2D",
  color_slot = "denovo_color"
) {




    text.halo.width = 0.1
    label_size = 0.8


    plot_coors = .get_plot_coors(ace, coordinate_attr)
    plot_labels = .get_plot_labels(label_attr, ace)
    plot_fill_col = .get_plot_colors(color_attr, plot_labels, ace, color_slot, palette)
    plot_alpha = .get_plot_transparency(trans_attr, ace, trans_fac, trans_th, TRUE)
    plot_border_col = colorspace::darken(plot_fill_col, stroke_contrast_fac)

    if(is.null(plot_labels) || !is.null(color_attr)){
      plot_labels = "NA"
      show_legend = FALSE
      names(plot_fill_col) = "NA"
      legend_labels = NULL
      legend_fill_breaks = NULL
    } else {
      names(plot_fill_col) = plot_labels
      legend_labels = sort(unique(plot_labels))
      legend_fill_breaks = plot_fill_col[legend_labels]
    }

    plot_data = data.frame(plot_coors,
      labels = plot_labels,
      fill = plot_fill_col,
      color = plot_border_col,
      trans = plot_alpha
    )

    # x = coors[, 1]
    # y = coors[, 2]
    # x.min = min(x)
    # x.max = max(x)
    # y.min = min(y)
    # y.max = max(y)
    # x.min = x.min - (x.max - x.min)/20
    # x.max = x.max + (x.max - x.min)/20
    # y.min = y.min - (y.max - y.min)/20
    # y.max = y.max + (y.max - y.min)/20
    # XL = c(x.min, x.max)
    # YL = c(y.min, y.max)
    rand_perm = sample(NROW(plot_data))
    p_out <- ggplot2::ggplot() +
         ggplot2::geom_point(
           data = plot_data[rand_perm, ],
           mapping = aes(
             x = x,
             y = y,
             color = color,
             fill = fill,
             alpha = trans
           ),
           shape = 21,
           size = point_size,
           stroke = stroke_size,
           show.legend = show_legend
         ) + scale_fill_identity(
           guide = "legend",
           breaks = legend_fill_breaks,
           labels = legend_labels
         ) +
         scale_color_identity() +
         scale_alpha_identity() +
         .default_ggtheme

    p_out
    # rand.perm = sample(nrow(coors))
    # graphics::plot(
    #   coors[rand.perm, c(1, 2)],
    #   pch = 21,
    #   cex = node_size,
    #   bg = vCol[rand.perm],
    #   col = vCol.border[rand.perm],
    #   axes = FALSE,
    #   xlab = "",
    #   ylab = "",
    #   main = title,
    #   xlim = XL,
    #   ylim = YL
    # )

    # if (add.text == TRUE & (!is.null(Annot))) {
    #     graphics::par(xpd = TRUE, mar = graphics::par()$mar * c(1.1, 1.1, 1.1, 1.1))
    #
    #     centroids = Matrix::t(sapply(Annot, function(l) {
    #         idx = which(names(labels) == l)
    #         if (length(idx) == 1) {
    #             return(as.numeric(coors[idx, ]))
    #         }
    #
    #         sub.coors = coors[idx, ]
    #         anchor.coor = as.numeric(apply(sub.coors, 2, function(x) mean(x, trim = 0.8)))
    #
    #         return(anchor.coor)
    #     }))

    #     layout.labels(
    #       x = centroids[, 1],
    #       y = centroids[, 2],
    #       labels = Annot,
    #       col = colorspace::darken(Pal, 0.5),
    #       bg = "#eeeeee",
    #       r = text.halo.width,
    #       cex = label_size
    #     )
    # }

    # if ((suppress.legend == FALSE) & !is.null(Annot)) {
    #     xmin <- graphics::par("usr")[1]
    #     xmax <- graphics::par("usr")[2]
    #     ymin <- graphics::par("usr")[3]
    #     ymax <- graphics::par("usr")[4]
    #
    #     lgd <- graphics::legend(
    #       x = mean(c(xmin, xmax)),
    #       y = mean(c(ymin, ymax)),
    #       legend = Annot,
    #       fill = Pal,
    #       cex = 0.5,
    #       bty = "n",
    #       plot = FALSE
    #     )
    #
    #     graphics::par(xpd = TRUE, mai = c(0, 0, 0, lgd$rect$w))
    #
    #
    # }
}
