CPal_default = c(
  "#1F77B4", "#FF7F0E", "#279E68", "#D62728", "#AA40FC", "#8C564B", "#E377C2", "#B5BD61", "#17BECF", "#AEC7E8",
  "#FFBB78", "#98DF8A", "#FF9896", "#C5B0D5", "#C49C94", "#F7B6D2", "#DBDB8D", "#9EDAE5", "#AD494A", "#8C6D31",
  "#E31A1C", "#FFD700", "#771122", "#777711", "#1F78B4", "#68228B", "#AAAA44", "#60CC52", "#771155", "#DDDD77",
  "#774411", "#AA7744", "#AA4455", "#117744", "#000080", "#44AA77", "#AA4488", "#DDAA77", "#D9D9D9", "#BC80BD",
  "#FFED6F", "#7FC97F", "#BEAED4", "#FDC086", "#FFFF99", "#386CB0", "#F0027F", "#BF5B17", "#666666", "#1B9E77",
  "#D95F02", "#7570B3", "#E7298A", "#66A61E", "#E6AB02", "#A6761D", "#A6CEE3", "#B2DF8A", "#33A02C", "#FB9A99",
  "#FDBF6F", "#FF7F00", "#CAB2D6", "#6A3D9A", "#B15928", "#FBB4AE", "#B3CDE3", "#CCEBC5", "#DECBE4", "#FED9A6",
  "#FFFFCC", "#E5D8BD", "#FDDAEC", "#F2F2F2", "#B3E2CD", "#FDCDAC", "#CBD5E8", "#F4CAE4", "#E6F5C9", "#FFF2AE",
  "#F1E2CC", "#CCCCCC", "#E41A1C", "#377EB8", "#4DAF4A", "#984EA3", "#FFFF33", "#A65628", "#F781BF", "#999999",
  "#66C2A5", "#FC8D62", "#8DA0CB", "#E78AC3", "#A6D854", "#FFD92F", "#E5C494", "#B3B3B3", "#8DD3C7", "#FFFFB3",
  "#BEBADA", "#FB8072", "#80B1D3", "#FDB462", "#B3DE69", "#FCCDE5"
)

.default_ggtheme <-  ggplot2::theme(axis.title = element_blank(),
        axis.text = ggplot2::element_blank(),
        axis.ticks = ggplot2::element_blank(),
        panel.background = ggplot2::element_blank(),
        legend.title = ggplot2::element_blank(),
        legend.background = ggplot2::element_blank(),
        legend.key = ggplot2::element_blank(),
        plot.margin = grid::unit(c(1,1,1,1),"lines"))

#' Main ACTIONet plotting functions
#'
#' @param ace 'ACTIONetExperiment' object or numeric matrix.
#' @param label_attr Character vector of length NROW(ace) or colname of 'colData(ace)' containing cell labels of interest (clusters, celltypes, etc.).
#' @param color_attr Character vector of length NROW(ace) or colname of 'colData(ace)' containing hex colors to use for each point, or matrix/data.frame containing RGB values to pass to grDevices::rgb().
#' @param trans_attr Numeric vector of length NROW(ace) or colname of 'colData(ace)' used to compute point transparency. Smaller values are more transparent (default:-0.5).
#' @param trans_fac Transparency modifier (default:1.5).
#' @param trans_th Minimum Z-score for which points with 'scale(trans_attr) < trans_th' are masked.
#' @param point_size Size of points in ggplot (default:1).
#' @param stroke_size Size of points outline (stroke) in ggplot (default:point_size*0.1).
#' @param stroke_contrast_fac Factor by which to darken point outline for contrast (default:0.1).
#' @param palette Color palette. character vector of hex colors or a palette name to pass to 'ggpubr::get_palette()').
#' @param add_text_labels Whether or not to add floating text labels on the top of annotated clusters. Ignored if 'label_attr=NULL'. (default:'TRUE').
#' @param text_size Size of floating text. Passed to 'ggplot2::geom_label()' (default:3).
#' @param nudge_text_labels Slightly offset labels proportional to cluster size so as to not cover small clusters (default:'TRUE').
#' @param show_legend Show legend based on labels. Ignored if 'label_attr=NULL' or 'color_attr!=NULL' (default:'FALSE').
#' @param coordinate_attr Name of entry in colMaps(ace) containing the plot coordinates (default:'ACTIONet2D').
#' @param color_slot Name of entry in colMaps(ace) containing RGB values for default point colors generated by 'layout_ACTIONet()'. Used only if no other coloring parameters are given or valid (default:'denovo_color').
#'
#' @return Visualized ACTIONet
#'
#' @examples
#' ace = run.ACTIONet(sce)
#' plot.ACTIONet(ace, ace$assigned_archetype, transparency.attr = ace$node_centrality)

#' @import ggplot2
#' @export
plot.ACTIONet <- function(
  ace,
  label_attr = NULL,
  color_attr = NULL,
  trans_attr = NULL,
  trans_fac = 1.5,
  trans_th = -0.5,
  point_size = 1,
  stroke_size = point_size * 0.1,
  stroke_contrast_fac = 0.1,
  palette = CPal_default,
  add_text_labels = TRUE,
  text_size = 3,
  nudge_text_labels = FALSE,
  show_legend = FALSE,
  coordinate_attr = "ACTIONet2D",
  color_slot = "denovo_color"
) {

    plot_coors = .get_plot_coors(ace, coordinate_attr)
    plot_labels = .get_plot_labels(label_attr, ace)
    plot_fill_col = .get_plot_colors(color_attr, plot_labels, ace, color_slot, palette)
    plot_alpha = .get_plot_transparency(trans_attr, ace, trans_fac, trans_th, TRUE)
    plot_border_col = colorspace::darken(plot_fill_col, stroke_contrast_fac)

    if(is.null(plot_labels)){
      data_labels = "NA"
      add_text_labels = FALSE
      show_legend = FALSE
      legend_labels = NULL
      legend_fill_colors = NULL
    } else {
      data_labels = plot_labels
      names(plot_fill_col) = plot_labels
      legend_labels = sort(unique(plot_labels))
      legend_fill_colors = plot_fill_col[legend_labels]
    }

    if(!is.null(color_attr)){
      show_legend = FALSE
      legend_fill_colors = NULL
    }

    plot_data = data.frame(plot_coors,
      labels = data_labels,
      fill = plot_fill_col,
      color = plot_border_col,
      trans = plot_alpha
    )

    rand_perm = sample(NROW(plot_data))
    p_out <- ggplot() +
         geom_point(
           data = plot_data[rand_perm, ],
           mapping = aes(
             x = x,
             y = y,
             color = color,
             fill = fill,
             alpha = trans
           ),
           shape = 21,
           size = point_size,
           stroke = stroke_size,
           show.legend = show_legend
         ) + scale_fill_identity(
           guide = "legend",
           labels = legend_labels,
           breaks = legend_fill_colors
         ) +
         scale_color_identity() +
         scale_alpha_identity() +
         .default_ggtheme

    if(!is.null(plot_labels) && add_text_labels ==  TRUE){
        p_out <- .layout_plot_labels(
          p_out,
          plot_data = plot_data,
          label_names = legend_labels,
          label_colors = legend_fill_colors,
          darken = TRUE,
          alpha_val = 0.5,
          text_size = text_size,
          constrast_fac = 0.5,
          nudge = nudge_text_labels
        )
    }

    p_out

}

#' @import ggplot2
.layout_plot_labels <- function(
  p,
  plot_data = NULL,
  label_names = NULL,
  label_colors = NULL,
  darken = TRUE,
  alpha_val = 0.5,
  text_size = 3,
  constrast_fac = 0.5,
  nudge = FALSE
) {

    if(is.null(label_names)){
      label_names = sort(unique(plot_data$labels))
    }

    label_coors = split(plot_data[, 1:2], plot_data$labels)
    label_coors = label_coors[label_names]
    centroids = lapply(label_coors, function(df){
      mat = as.matrix(df)
      cent = apply(mat, 2, function(x) mean(x, trim = 0.25))
      return(cent)
    })

    cent_sd = lapply(label_coors, function(df){
      mat = as.matrix(df)
      cent_sd = apply(mat, 2, sd)
      return(cent_sd)
    })
    cent_sd = do.call(rbind, cent_sd)
    colnames(cent_sd) = c("x_sd", "y_sd")

    if(is.null(label_colors)){
      label_colors = rep("black", length(label_names))
    } else {
        if(darken == TRUE)
          label_colors = colorspace::darken(label_colors, constrast_fac)
    }

    layout_data = data.frame(do.call(rbind, centroids),
                             cent_sd,
                             labels = names(centroids),
                             color = label_colors
                           )

    layout_data[, c("x", "y")] = gplots::space(layout_data$x, layout_data$y, s=c(1/20, 1/5), na.rm=TRUE, direction="y")

    if(nudge == TRUE){
      layout_data$x = layout_data$x + (1 - exp(-0.5 * abs(layout_data$x_sd - max(layout_data$x_sd))))
      layout_data$y = layout_data$y + (1 - exp(-0.5 * abs(layout_data$y_sd - max(layout_data$y_sd))))
    }

    p <- p + geom_label(
      data = layout_data,
      mapping = aes(
        x = x,
        y = y,
        label = labels,
        color = color
      ),
      fill = scales::alpha(c("white"), alpha_val),
      size = text_size)

  return(p)
}
